-- 0002_analytics_schema: 11 bang tu powerBI/*.csv (dim_*, fact_*).
-- Thiet ke + ly do: docs/d1-schema-design.md muc 4. Thu tu tao = thu tu nap (dim truoc fact)
-- vi co FOREIGN KEY. Khong index phu (nap mot lan, doc it); them bang migration sau neu can.

CREATE TABLE dim_region (
  region_id TEXT PRIMARY KEY,
  region_name TEXT NOT NULL,
  tier TEXT NOT NULL
) WITHOUT ROWID;

CREATE TABLE dim_hex (
  hex_id TEXT PRIMARY KEY,
  region_id TEXT NOT NULL,
  nearest_district TEXT NOT NULL,
  center_lat REAL NOT NULL,
  center_lng REAL NOT NULL,
  hex_tier TEXT NOT NULL,
  h3_resolution INTEGER NOT NULL,
  FOREIGN KEY (region_id) REFERENCES dim_region(region_id)
) WITHOUT ROWID;

CREATE TABLE dim_promo (
  promo_code TEXT PRIMARY KEY,
  promo_name TEXT NOT NULL,
  service TEXT NOT NULL,
  vehicle_scope TEXT NOT NULL,
  discount_type TEXT NOT NULL,
  discount_target TEXT NOT NULL,
  discount_value REAL NOT NULL,
  max_discount INTEGER NOT NULL,
  min_order_value INTEGER NOT NULL,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  has_cap_change INTEGER NOT NULL CHECK (has_cap_change IN (0, 1))
) WITHOUT ROWID;

CREATE TABLE dim_promo_cap_history (
  promo_code TEXT NOT NULL,
  cap_version_id TEXT PRIMARY KEY,
  effective_from TEXT NOT NULL,
  effective_to TEXT NOT NULL,
  discount_rate_or_value REAL NOT NULL,
  max_discount INTEGER NOT NULL,
  min_order_value INTEGER NOT NULL,
  FOREIGN KEY (promo_code) REFERENCES dim_promo(promo_code)
) WITHOUT ROWID;

CREATE TABLE dim_date (
  date_key INTEGER PRIMARY KEY,
  date TEXT NOT NULL,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  month_name TEXT NOT NULL,
  day INTEGER NOT NULL,
  weekday_no INTEGER NOT NULL,
  weekday_name TEXT NOT NULL,
  is_weekend INTEGER NOT NULL CHECK (is_weekend IN (0, 1)),
  week_of_year INTEGER NOT NULL,
  month_start TEXT NOT NULL,
  campaign TEXT,
  is_campaign_day INTEGER NOT NULL CHECK (is_campaign_day IN (0, 1))
) WITHOUT ROWID;

CREATE TABLE dim_merchant (
  merchant_id TEXT PRIMARY KEY,
  merchant_name TEXT NOT NULL,
  cuisine TEXT NOT NULL,
  hex_id TEXT NOT NULL,
  region_id TEXT NOT NULL,
  avg_rating REAL NOT NULL,
  avg_prep_min INTEGER NOT NULL,
  FOREIGN KEY (hex_id) REFERENCES dim_hex(hex_id),
  FOREIGN KEY (region_id) REFERENCES dim_region(region_id)
) WITHOUT ROWID;

CREATE TABLE dim_user (
  user_id TEXT PRIMARY KEY,
  segment TEXT NOT NULL,
  signup_date TEXT NOT NULL,
  home_region_id TEXT NOT NULL,
  home_hex_id TEXT NOT NULL,
  age_group TEXT NOT NULL,
  promo_group TEXT NOT NULL,
  FOREIGN KEY (home_hex_id) REFERENCES dim_hex(hex_id)
) WITHOUT ROWID;

CREATE TABLE fact_promo_budget (
  month_start TEXT,
  service TEXT,
  region_id TEXT NOT NULL,
  hex_id TEXT,
  segment TEXT,
  budget_vnd INTEGER NOT NULL,
  PRIMARY KEY (month_start, service, hex_id, segment),
  FOREIGN KEY (hex_id) REFERENCES dim_hex(hex_id)
) WITHOUT ROWID;

CREATE TABLE fact_ride (
  session_id TEXT PRIMARY KEY,
  date_key INTEGER NOT NULL,
  session_start TEXT NOT NULL,
  session_hour INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  segment TEXT NOT NULL,
  promo_group TEXT NOT NULL,
  region_id TEXT NOT NULL,
  hex_id TEXT NOT NULL,
  dropoff_hex_id TEXT NOT NULL,
  service_type TEXT NOT NULL,
  vehicle_type TEXT NOT NULL,
  distance_km REAL NOT NULL,
  est_duration_min INTEGER NOT NULL,
  is_peak_hour INTEGER NOT NULL CHECK (is_peak_hour IN (0, 1)),
  is_rainy INTEGER NOT NULL CHECK (is_rainy IN (0, 1)),
  is_campaign_day INTEGER NOT NULL CHECK (is_campaign_day IN (0, 1)),
  surge_multiplier REAL NOT NULL,
  gmv_before_promo INTEGER NOT NULL,
  entry_point TEXT NOT NULL,
  n_promos_eligible INTEGER NOT NULL,
  best_eligible_discount INTEGER NOT NULL,
  promo_viewed INTEGER NOT NULL CHECK (promo_viewed IN (0, 1)),
  n_promos_viewed INTEGER NOT NULL,
  promo_removed_code TEXT,
  n_clicks INTEGER NOT NULL,
  time_on_price_screen_sec INTEGER NOT NULL,
  time_on_promo_screen_sec REAL,
  session_duration_sec INTEGER NOT NULL,
  time_to_confirm_sec REAL,
  promo_code TEXT,
  cap_version_id TEXT,
  discount_target TEXT,
  discount_type TEXT,
  discount_rate REAL,
  min_order_value REAL,
  discount_before_cap INTEGER NOT NULL,
  max_discount REAL,
  discount_shown_amount INTEGER NOT NULL,
  cap_applied INTEGER NOT NULL CHECK (cap_applied IN (0, 1)),
  cap_lost_amount INTEGER NOT NULL,
  session_outcome TEXT NOT NULL,
  drop_stage TEXT,
  wait_time_min REAL,
  cancel_by TEXT,
  cancel_reason TEXT,
  burn_amount INTEGER NOT NULL,
  amount_paid INTEGER NOT NULL,
  payment_method TEXT,
  driver_rating REAL,
  FOREIGN KEY (user_id) REFERENCES dim_user(user_id),
  FOREIGN KEY (hex_id) REFERENCES dim_hex(hex_id),
  FOREIGN KEY (dropoff_hex_id) REFERENCES dim_hex(hex_id),
  FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
  FOREIGN KEY (promo_code) REFERENCES dim_promo(promo_code),
  FOREIGN KEY (cap_version_id) REFERENCES dim_promo_cap_history(cap_version_id)
) WITHOUT ROWID;

CREATE TABLE fact_food (
  session_id TEXT PRIMARY KEY,
  date_key INTEGER NOT NULL,
  session_start TEXT NOT NULL,
  session_hour INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  segment TEXT NOT NULL,
  promo_group TEXT NOT NULL,
  region_id TEXT NOT NULL,
  hex_id TEXT NOT NULL,
  merchant_id TEXT NOT NULL,
  merchant_hex_id TEXT NOT NULL,
  cuisine TEXT NOT NULL,
  num_items INTEGER NOT NULL,
  distance_km REAL NOT NULL,
  is_peak_hour INTEGER NOT NULL CHECK (is_peak_hour IN (0, 1)),
  is_rainy INTEGER NOT NULL CHECK (is_rainy IN (0, 1)),
  is_campaign_day INTEGER NOT NULL CHECK (is_campaign_day IN (0, 1)),
  food_subtotal INTEGER NOT NULL,
  delivery_fee INTEGER NOT NULL,
  surge_fee INTEGER NOT NULL,
  platform_fee INTEGER NOT NULL,
  gmv_before_promo INTEGER NOT NULL,
  topped_up_to_qualify INTEGER NOT NULL CHECK (topped_up_to_qualify IN (0, 1)),
  entry_point TEXT NOT NULL,
  n_promos_eligible INTEGER NOT NULL,
  best_eligible_discount INTEGER NOT NULL,
  promo_viewed INTEGER NOT NULL CHECK (promo_viewed IN (0, 1)),
  n_promos_viewed INTEGER NOT NULL,
  promo_removed_code TEXT,
  n_clicks INTEGER NOT NULL,
  time_on_price_screen_sec INTEGER NOT NULL,
  time_on_promo_screen_sec REAL,
  session_duration_sec INTEGER NOT NULL,
  time_to_confirm_sec REAL,
  promo_code TEXT,
  cap_version_id TEXT,
  discount_target TEXT,
  discount_type TEXT,
  discount_rate REAL,
  min_order_value REAL,
  discount_before_cap INTEGER NOT NULL,
  max_discount REAL,
  discount_shown_amount INTEGER NOT NULL,
  cap_applied INTEGER NOT NULL CHECK (cap_applied IN (0, 1)),
  cap_lost_amount INTEGER NOT NULL,
  session_outcome TEXT NOT NULL,
  drop_stage TEXT,
  prep_time_min REAL,
  cancel_by TEXT,
  cancel_reason TEXT,
  burn_amount INTEGER NOT NULL,
  amount_paid INTEGER NOT NULL,
  payment_method TEXT,
  delivery_time_min REAL,
  food_rating REAL,
  FOREIGN KEY (user_id) REFERENCES dim_user(user_id),
  FOREIGN KEY (hex_id) REFERENCES dim_hex(hex_id),
  FOREIGN KEY (merchant_id) REFERENCES dim_merchant(merchant_id),
  FOREIGN KEY (merchant_hex_id) REFERENCES dim_hex(hex_id),
  FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
  FOREIGN KEY (promo_code) REFERENCES dim_promo(promo_code),
  FOREIGN KEY (cap_version_id) REFERENCES dim_promo_cap_history(cap_version_id)
) WITHOUT ROWID;

CREATE TABLE fact_promo_burn (
  burn_event_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  service TEXT NOT NULL,
  event_datetime TEXT NOT NULL,
  date_key INTEGER NOT NULL,
  user_id TEXT NOT NULL,
  segment TEXT NOT NULL,
  promo_group TEXT NOT NULL,
  promo_code TEXT NOT NULL,
  cap_version_id TEXT NOT NULL,
  region_id TEXT NOT NULL,
  hex_id TEXT NOT NULL,
  gmv_before_promo INTEGER NOT NULL,
  discount_before_cap INTEGER NOT NULL,
  max_discount REAL NOT NULL,
  cap_applied INTEGER NOT NULL CHECK (cap_applied IN (0, 1)),
  cap_lost_amount INTEGER NOT NULL,
  reserved_burn INTEGER NOT NULL,
  is_trip_completed INTEGER NOT NULL CHECK (is_trip_completed IN (0, 1)),
  realized_burn INTEGER NOT NULL,
  wasted_burn INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES dim_user(user_id),
  FOREIGN KEY (hex_id) REFERENCES dim_hex(hex_id),
  FOREIGN KEY (date_key) REFERENCES dim_date(date_key),
  FOREIGN KEY (promo_code) REFERENCES dim_promo(promo_code),
  FOREIGN KEY (cap_version_id) REFERENCES dim_promo_cap_history(cap_version_id)
) WITHOUT ROWID;
